"""create transcriptions

Revision ID: b435e14d74c1
Revises:
Create Date: 2026-10-03 06:21:15.571199
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b435e14d74c1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.Column(
            "status", sa.Enum("pending", "processing", "done", "failed", name="transcription_status"), nullable=False
        ),
        sa.Column("task", sa.Enum("transcribe", "translate", name="transcription_task"), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("audio_path", sa.String(length=512), nullable=True),
        sa.Column("requested_language", sa.String(length=8), nullable=True),
        sa.Column("detected_language", sa.String(length=8), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("segments", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("model_name", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transcriptions_expires_at"), "transcriptions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_transcriptions_slug"), "transcriptions", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transcriptions_slug"), table_name="transcriptions")
    op.drop_index(op.f("ix_transcriptions_expires_at"), table_name="transcriptions")
    op.drop_table("transcriptions")
    sa.Enum(name="transcription_task").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="transcription_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
